### ISSUE TITLE
currency indicator in front of number

### ISSUE THREAD

**Issue by corebots** [OttoAllmendinger/gnome-shell-bitcoin-markets#73]
Please can you move the currency indicator (USD, EUR/BTC,...) to the front of the shown number? See http://publications.europa.eu/code/en/en-370303.htm for correct way of displaying monetary units.

**Comment by OttoAllmendinger** [comment]
I could add it as an option

BTW your link doesn't work

**Comment by corebots** [comment]
The link basically only lists and explains cases of writing amounts and the currencies are in front of the numbers...(link works for me so not sure what the problem is) So I thought for better legibility maybe this could be changed/added as an option. But not a big deal i guess... anyway thanks

**Comment by OttoAllmendinger** [comment]
I added a more flexible way of customizing the ticker text

![image](https://user-images.githubusercontent.com/283533/50052892-ed6bd780-012b-11e9-8429-429519b6afe8.png)

I think this should satisfy all preferences

**Comment by corebots** [comment]
thanks, that looks nice. I've tried it out, but it's a bit weired, at least on for Kraken. the currency symbols aren't shown. Maybe I need to install some symbols? for Kraken one needs to enter XXBT instead of XBT for bitcoin, then the same char-sequence is shown in the panel instead of the symbol. Any chance you could check on that? not a big deal since one can type the currency as text manually, but symbols would be cool ;)
![screenshot from 2019-01-11 14-42-33](https://user-images.githubusercontent.com/12252430/51037284-1149fe00-15b0-11e9-98ad-cfea2d3dcc31.png)

**Comment by OttoAllmendinger** [comment]
Symbols (like `$`, `€` etc) are currently are only supported for fiat currencies. 

For crypto quotes, it falls back to the ticker code. Especially for exchanges like Kraken that can be weird.

I decided that it is easier for the users to deal with API naming weirdness, since any attempts by me to normalize the ticker names will be incomplete and obsolete very quickly. 

However you can use `{btc}` to get the bitcoin symbol (`₿`). I'm not up to speed with the other symbols used in the crypto world, but if you can point me to a place where I can find them, I can add more.

Other than that, I suggest users manually enter `BTC` or whatever they prefer :)
